// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaLI1TfZHvoXsReoN835belOnZiuGclCI',
    appId: '1:99822796606:web:55538a4bad2195b549b66f',
    messagingSenderId: '99822796606',
    projectId: 'lokasee-49f93',
    authDomain: 'lokasee-49f93.firebaseapp.com',
    storageBucket: 'lokasee-49f93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVDEDZTD9VLWYh1x8iJlRP1X0rH0NBJNE',
    appId: '1:99822796606:android:06eff7cfb89c8fee49b66f',
    messagingSenderId: '99822796606',
    projectId: 'lokasee-49f93',
    storageBucket: 'lokasee-49f93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9EqQxi8-FmkXdcT3Mz5j7MQeBIqAo0Y',
    appId: '1:99822796606:ios:edeeb13fd77f639149b66f',
    messagingSenderId: '99822796606',
    projectId: 'lokasee-49f93',
    storageBucket: 'lokasee-49f93.firebasestorage.app',
    iosBundleId: 'com.example.venuebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9EqQxi8-FmkXdcT3Mz5j7MQeBIqAo0Y',
    appId: '1:99822796606:ios:edeeb13fd77f639149b66f',
    messagingSenderId: '99822796606',
    projectId: 'lokasee-49f93',
    storageBucket: 'lokasee-49f93.firebasestorage.app',
    iosBundleId: 'com.example.venuebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaLI1TfZHvoXsReoN835belOnZiuGclCI',
    appId: '1:99822796606:web:7f3b8de3ee38d16349b66f',
    messagingSenderId: '99822796606',
    projectId: 'lokasee-49f93',
    authDomain: 'lokasee-49f93.firebaseapp.com',
    storageBucket: 'lokasee-49f93.firebasestorage.app',
  );
}
